name: Build Ruby for GitHub Actions
on: [push]
jobs:
  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Create tag
      id: create_tag
      run: |
        tag=builds-`date +%Y%m%d-%H%M%S`
        git tag $tag
        git push origin $tag
        echo "::set-output name=tag::$tag"
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.create_tag.outputs.tag }}
        release_name: ${{ steps.create_tag.outputs.tag }}
        draft: true
        prerelease: false
    - name: Create upload_url.txt file
      run: echo "${{ steps.create_release.outputs.upload_url }}" > upload_url.txt
    - uses: actions/upload-artifact@v1
      with:
        name: upload_url
        path: upload_url.txt

  build:
    needs: [release]
    strategy:
      fail-fast: false
      matrix:
        os: [ 'ubuntu-16.04', 'ubuntu-18.04', 'macos-latest' ]
        ruby: [ 'ruby-2.4.9', 'ruby-2.5.7', 'ruby-2.6.5', 'ruby-2.7.0', 'truffleruby-19.3.0', 'jruby-9.2.9.0' ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/download-artifact@v1
      with:
        name: upload_url
    - name: Set upload_url
      id: release_info
      run: |
        upload_url=`cat upload_url/upload_url.txt`
        echo "::set-output name=upload_url::$upload_url"

    - name: Clone ruby-install
      run: git clone https://github.com/postmodern/ruby-install.git
    - name: Install ruby-install
      run: sudo make install
      working-directory: ./ruby-install

    - name: List versions
      run: ruby-install
    - name: apt-get update on Ubuntu
      run: sudo apt-get update
      if: startsWith(matrix.os, 'ubuntu')
    - name: Build Ruby
      run: ruby-install ${{ matrix.ruby }} -- --disable-install-doc
    - name: Install Bundler if needed
      run: |
        if [ ! -e ~/.rubies/${{ matrix.ruby }}/bin/bundle ]; then
          export PATH="$HOME/.rubies/${{ matrix.ruby }}/bin:$PATH"
          gem install bundler --no-document
        fi
    - name: Basic test
      run: ~/.rubies/${{ matrix.ruby }}/bin/ruby --version

    - name: Create archive
      run: tar czf ${{ matrix.ruby }}-${{ matrix.os }}.tar.gz -C ~/.rubies ${{ matrix.ruby }}
    - name: Upload Built Ruby
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.release_info.outputs.upload_url }}
        asset_path: ${{ matrix.ruby }}-${{ matrix.os }}.tar.gz
        asset_name: ${{ matrix.ruby }}-${{ matrix.os }}.tar.gz
        asset_content_type: application/gzip
